spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:testdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

services.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
services.user-service.name=${USER_SERVICE_NAME:user-service}

keycloak.server-url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:Oauth}

spring.security.oauth2.client.registration.keycloak-internal.authorization-grant-type=client_credentials

keycloak.token-url=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect
spring.security.oauth2.client.registration.keycloak-internal.client-id=${KEYCLOAK_CLIENT_ID:auth-service-client}
spring.security.oauth2.client.registration.keycloak-internal.client-secret=${KEYCLOAK_CLIENT_SECRET:mock-secret}

spring.security.oauth2.client.provider.keycloak-internal.token-uri=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak.local:8081/realms/user-service