spring.datasource.url=jdbc:postgresql://localhost:5432/orderservice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379

services.user-service.url=${USER_SERVICE_URL}
services.user-service.name=${USER_SERVICE_NAME}