name: Spring CI
on:
  push:
    branches:
      - main
      - order-service
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build
        run: mvn clean compile

      - name: Run Tests
        run: mvn verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=GritsH_innowise-order-service
          -Dsonar.organization=gritsh
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN

      - name: Build Docker image
        run: docker build -t order-service:${{ github.sha }} .